routes/web.php
<?php

use Illuminate\Foundation\Application;
use Illuminate\Support\Facades\Route;
use Inertia\Inertia;


use App\Http\Controllers\Home\AppSettings;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return Inertia::render('Auth/Login', [
        'canRegister' => Route::has('register'),
    ]);
}) ->name('guest_home');

Route::get('/SuccessPage', function () {
    return Inertia::render('SucessPage', [
        'canRegister' => Route::has('register'),
   
    ]);
}) ->name('SuccessPage');

Route::get('/Aboutus', function () {
    return Inertia::render('AboutUs', [
        'canRegister' => Route::has('register'),
   
    ]);
}) ->name('aboutus');





Route::get('/Resources', function () {
    return Inertia::render('Resources', [
        'canRegister' => Route::has('register'),
   
    ]);
}) ->name('faq');

Route::get('/checkstatus', function () {
    return Inertia::render('Checkstatus');
})->name('checkstatus');

Route::get('/Ref', function () {
    return Inertia::render('Ref');
})->name('ref');
Route::get('/SupportForm', function () {
    return Inertia::render('SupportForm');
})->name('supportform');


Route::post('users', [AppSettings::class, 'RoleChange'])->name('rolechange');
Route::post('outgoings', [AppSettings::class, 'outgoing'])->name('outgoing');
Route::post('incomings', [AppSettings::class, 'incoming'])->name('incoming');
Route::post('users.add', [AppSettings::class, 'AddUser'])->name('adduser');
Route::post('signature', [AppSettings::class, 'addsignature'])->name('addsigs');
Route::post('incoming', [AppSettings::class, 'addincoming'])->name('addincoming');






require __DIR__.'/auth.php';

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title inertia>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
      
        <link rel="stylesheet" href="{{ asset(mix('css/app.css')) }}">
        <!-- Scripts -->
        @routes
        <script src="{{ asset(mix('js/app.js')) }}" defer></script>
    </head>
    <body class="font-sans antialiased">
        @inertia
    </body>
</html>

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    You're logged in!
                </div>
            </div>
        </div>
    </div>
</x-app-layout>